List

In [2]:
sample_list=[1,13.6,"hello",12,1]
sample_list

[1, 13.6, 'hello', 12, 1]

In [3]:
sample_list[2]

'hello'

In [4]:
sample_list[-1]

1

In [5]:
sample_list[-3]

'hello'

In [6]:
sample_list[1]="Shruti"
sample_list

[1, 'Shruti', 'hello', 12, 1]

Tuple

In [7]:
sample_tuple=(1,13.6,"Shruti","HEY",12,1)
sample_tuple

(1, 13.6, 'Shruti', 'HEY', 12, 1)

In [8]:
sample_tuple[2]

'Shruti'

In [9]:
sample_tuple[-1]

1

In [10]:
sample_tuple[2]=54
sample_tuple

TypeError: 'tuple' object does not support item assignment

Dictionary

In [11]:
sample_dict={1:"XYZ",2:54.34,5:"Shruti",6:12}
sample_dict

{1: 'XYZ', 2: 54.34, 5: 'Shruti', 6: 12}

In [12]:
sample_dict[2]

54.34

In [13]:
sample_dict[4]

KeyError: 4

In [14]:
sample_dict[3]="DATA SCIENCE"
sample_dict

{1: 'XYZ', 2: 54.34, 5: 'Shruti', 6: 12, 3: 'DATA SCIENCE'}

In [15]:
sample_dict[4]=2
sample_dict

{1: 'XYZ', 2: 54.34, 5: 'Shruti', 6: 12, 3: 'DATA SCIENCE', 4: 2}

In [16]:
sample_dict[2]=4
sample_dict

{1: 'XYZ', 2: 4, 5: 'Shruti', 6: 12, 3: 'DATA SCIENCE', 4: 2}

In [17]:
sample_dict={1:456,2:"XYZ",3:54.82,2:"Fine"}
sample_dict

{1: 456, 2: 'Fine', 3: 54.82}

Set

In [18]:
sample_set={1,27,,"ABC",13.6,156,"frog","12","Ball"}
sample_set

SyntaxError: invalid syntax (3224710609.py, line 1)

In [19]:
sample_set={1,27,"ABC",13.6,156,"frog","12","Ball"}
sample_set

{1, '12', 13.6, 156, 27, 'ABC', 'Ball', 'frog'}

In [20]:
sample_set.add(5000)
sample_set

{1, '12', 13.6, 156, 27, 5000, 'ABC', 'Ball', 'frog'}

In [21]:
sample_set.remove("frog")
sample_set

{1, '12', 13.6, 156, 27, 5000, 'ABC', 'Ball'}

In [22]:
sample_set[1]

TypeError: 'set' object is not subscriptable

Numpy

In [23]:
import numpy as np

In [24]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [25]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(1,50)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [28]:
np.arange(1,46,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41])

In [29]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [30]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [31]:
np.zeros(5,int)

array([0, 0, 0, 0, 0])

In [32]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [33]:
np.ones((2,5),int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

linspace

In [34]:
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [35]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [36]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])